name: Deploy to Staging

on:
  push:
    branches:
      - main
      - develop

permissions:
  contents: write # Cấp quyền write cho việc quản lý file và nội dung trong repo
  deployments: write # Cấp quyền write để thực hiện deployment

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20" # Sử dụng phiên bản Node.js đã ổn định (Node.js 22 có thể gặp vấn đề không tương thích)

      - name: Install dependencies
        run: npm install

      - name: Build TailwindCSS
        run: npx tailwindcss -i ./src/input.css -o ./dist/output.css --minify

      - name: Build the Ezinn Admin app
        run: npm run build

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build --no-cache -t ${{ secrets.DOCKER_USERNAME }}/ezinn-admin:staging .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/ezinn-admin:staging

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }} # Sử dụng mật khẩu để đăng nhập
          port: 22
          script: |
            docker stop ezinn-admin || true
            docker rm ezinn-admin || true
            docker pull ${{ secrets.DOCKER_USERNAME }}/ezinn-admin:staging
            docker run -d --name ezinn-admin -p 3001:3001 ${{ secrets.DOCKER_USERNAME }}/ezinn-admin:staging

      - name: Run deployment action in Jira
        uses: chrnorm/deployment-action@releases/v1
        with:
          environment: "staging"
          token: ${{ secrets.GITHUB_TOKEN }}
          description: "Deploying ezinn-admin to staging via Docker"
